-- MySQL Script generated by MySQL Workbench
-- 12/20/15 22:46:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema qlnk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema qlnk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qlnk` DEFAULT CHARACTER SET utf8 ;
USE `qlnk` ;

-- -----------------------------------------------------
-- Table `qlnk`.`canbo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qlnk`.`canbo` (
  `TaiKhoan` CHAR(20) NOT NULL DEFAULT '' COMMENT '',
  `MatKhau` CHAR(20) NOT NULL COMMENT '',
  `NgayCapNhat` VARCHAR(20) NOT NULL COMMENT '',
  `Quyen` INT(11) NOT NULL COMMENT '',
  `NguoiSuDung` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`TaiKhoan`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `qlnk`.`chungtu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qlnk`.`chungtu` (
  `MCT` CHAR(10) NOT NULL DEFAULT '' COMMENT '',
  `TenNguoiKhai` VARCHAR(50) NOT NULL COMMENT '',
  `ThuongTamTru` VARCHAR(100) NOT NULL COMMENT '',
  `QHVoiNguoiMat` VARCHAR(20) NOT NULL COMMENT '',
  `TenNguoiMat` VARCHAR(50) NOT NULL COMMENT '',
  `NgaySinh` CHAR(10) NOT NULL COMMENT '',
  `DanToc` VARCHAR(20) NULL DEFAULT NULL COMMENT '',
  `QuocTich` VARCHAR(20) NOT NULL COMMENT '',
  `CMND` CHAR(9) NULL DEFAULT NULL COMMENT '',
  `NgayMat` CHAR(10) NOT NULL COMMENT '',
  `GioMat` CHAR(5) NOT NULL COMMENT '',
  `KVDK` VARCHAR(20) NOT NULL COMMENT '',
  `NgayDK` CHAR(10) NOT NULL COMMENT '',
  PRIMARY KEY (`MCT`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `qlnk`.`hokhau`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qlnk`.`hokhau` (
  `MHK` CHAR(10) NOT NULL DEFAULT '' COMMENT '',
  `TenChuHo` VARCHAR(50) NOT NULL COMMENT '',
  `CMNDChuHo` CHAR(9) NOT NULL COMMENT '',
  `KhuVuc` VARCHAR(50) NOT NULL COMMENT '',
  `DiaChiHK` VARCHAR(100) NOT NULL COMMENT '',
  `NgayLap` CHAR(10) NOT NULL COMMENT '',
  PRIMARY KEY (`MHK`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `qlnk`.`kethon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qlnk`.`kethon` (
  `MKH` CHAR(10) NOT NULL DEFAULT '' COMMENT '',
  `TenChong` VARCHAR(50) NOT NULL COMMENT '',
  `NgaySinhChong` CHAR(10) NOT NULL COMMENT '',
  `DanTocChong` VARCHAR(20) NOT NULL COMMENT '',
  `QueQuanChong` VARCHAR(20) NOT NULL COMMENT '',
  `ThuongTamTruChong` VARCHAR(100) NOT NULL COMMENT '',
  `CMNDChong` CHAR(9) NOT NULL COMMENT '',
  `TenVo` VARCHAR(50) NOT NULL COMMENT '',
  `NgaySinhVo` CHAR(10) NOT NULL COMMENT '',
  `DanTocVo` VARCHAR(20) NOT NULL COMMENT '',
  `QueQuanVo` VARCHAR(20) NOT NULL COMMENT '',
  `ThuongTamTruVo` VARCHAR(100) NOT NULL COMMENT '',
  `CMNDVo` CHAR(9) NOT NULL COMMENT '',
  `KVDK` VARCHAR(20) NOT NULL COMMENT '',
  `NgayDK` CHAR(10) NOT NULL COMMENT '',
  PRIMARY KEY (`MKH`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `qlnk`.`nhankhau`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qlnk`.`nhankhau` (
  `MNK` CHAR(10) NOT NULL DEFAULT '' COMMENT '',
  `Ten` VARCHAR(50) NOT NULL COMMENT '',
  `NgaySinh` CHAR(10) NOT NULL COMMENT '',
  `GioiTinh` CHAR(3) NOT NULL COMMENT '',
  `QueQuan` VARCHAR(20) NOT NULL COMMENT '',
  `TonGiao` VARCHAR(20) NOT NULL COMMENT '',
  `DanToc` VARCHAR(20) NOT NULL COMMENT '',
  `CMND` CHAR(9) NULL DEFAULT NULL COMMENT '',
  `MHK` CHAR(10) NOT NULL COMMENT '',
  `NgheNghiep` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`MNK`)  COMMENT '',
  INDEX `nhankhau_ibfk_1` (`MHK` ASC)  COMMENT '',
  CONSTRAINT `nhankhau_ibfk_1`
    FOREIGN KEY (`MHK`)
    REFERENCES `qlnk`.`hokhau` (`MHK`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `qlnk`.`tamtru`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qlnk`.`tamtru` (
  `MTT` CHAR(10) NOT NULL DEFAULT '' COMMENT '',
  `MNK` CHAR(10) NOT NULL COMMENT '',
  `TenNoiTamTru` VARCHAR(50) NOT NULL COMMENT '',
  `DiaChi` VARCHAR(100) NOT NULL COMMENT '',
  `SoDienThoai` CHAR(11) NOT NULL COMMENT '',
  `ThoiHan` CHAR(10) NOT NULL COMMENT '',
  PRIMARY KEY (`MTT`)  COMMENT '',
  INDEX `tamtru_ibfk_1` (`MNK` ASC)  COMMENT '',
  CONSTRAINT `tamtru_ibfk_1`
    FOREIGN KEY (`MNK`)
    REFERENCES `qlnk`.`nhankhau` (`MNK`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `qlnk`.`tienantiensu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qlnk`.`tienantiensu` (
  `MaTATS` CHAR(10) NOT NULL DEFAULT '' COMMENT '',
  `MNK` CHAR(10) NOT NULL COMMENT '',
  `TenTATS` VARCHAR(50) NOT NULL COMMENT '',
  `NoiXetXu` VARCHAR(20) NOT NULL COMMENT '',
  `NgayThucThi` CHAR(10) NOT NULL COMMENT '',
  PRIMARY KEY (`MaTATS`)  COMMENT '',
  INDEX `tienantiensu_ibfk_1` (`MNK` ASC)  COMMENT '',
  CONSTRAINT `tienantiensu_ibfk_1`
    FOREIGN KEY (`MNK`)
    REFERENCES `qlnk`.`nhankhau` (`MNK`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
